[package]
name = "boatbomber/encryptednet"
description = "Authenticated encryption of Roblox networking with ECDH key exchanges and ChaCha20 ciphering."
version = "1.0.2"
license = "MIT"
authors = ["boatbomber (https://boatbomber.com)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]
